name: Build xdelta3 Binaries

on:
  push:
    branches: [ main ] # Запускать при пуше в main
  workflow_dispatch:   # Позволяет запускать вручную

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: macos-latest
            arch: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            arch: arm64
            target: aarch64-apple-darwin
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout xdelta source code
      uses: actions/checkout@v3
      with:
        repository: jmacd/xdelta
        ref: 'v3.1.0' # Стабильная версия

    - name: Set up build environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Build on Linux
      if: runner.os == 'Linux'
      run: |
        make -C xdelta3
        mv xdelta3/xdelta3 ./xdelta3-linux-x64

    - name: Build on macOS
      if: runner.os == 'macOS'
      run: |
        export CFLAGS="-arch ${{ matrix.arch }}"
        make -C xdelta3
        mv xdelta3/xdelta3 ./xdelta3-macos-${{ matrix.arch }}
        
    - name: Build on Windows
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-gcc make
        make -C xdelta3
        mv xdelta3/xdelta3.exe ./xdelta3-win-x64.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: xdelta3-binaries-${{ runner.os }}-${{ matrix.arch || 'x64' }}
        path: |
          xdelta3-linux-x64
          xdelta3-macos-*
          xdelta3-win-x64.exe
        if-no-files-found: error
